apiVersion: v1
kind: Service
metadata:
  name: Cravyto 
  labels:
    app: Cravyto 
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001
  selector:
    app: Cravyto 
